version: '2'
services:
  
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: chat-server
    volumes:
      - "./app:/app"
    ports:
      - "8081:8080"
    command: python /app/server.py

  client:
    image: nginx
    container_name: chat-client
    ports:
      - "81:80" 
    volumes:
      - ./app:/usr/share/nginx/html
  mongodb:
    image: mongo:3.0.2
    container_name: chat-mongo
    volumes:
        - ./mongodb:/data/db