version: '2'
services:
  
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: chat-server
    volumes:
      - "./app:/app"
    ports:
      - "8081:8080"
      - "9999:9999"
    command: python /app/server.py
    
  mongodb:
    image: mongo:3.0.2
    container_name: chat-mongo
    volumes:
        - ./mongodb:/data/db